use_frameworks!

platform :ios, '9.0'

target 'XMaterialProgressView_Example' do
  pod 'XMaterialProgressView', :path => '../'

  target 'XMaterialProgressView_Tests' do
    inherit! :search_paths

    
  end
end
